name: Run Tests

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name:  actions/setup-ruby@v1
      with:
        ruby-version: '2.5.5'
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Run Tests
      run: bundle exec rspec
