name: Run Tests

on:
  push:
    branches: [ trunk ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ trunk ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v1
    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.2'
    - name: install deps
      run: |
        gem install bundler -v 1.17.3
        bundle install
    - name: run tests
      run: bundle exec rspec
