name: StandardRB

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: StandardRB Linter
      uses: andrewmcodes/standardrb-action@v0.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
